### PR TITLE
Fix Jenkins workflow

### PR DESCRIPTION
**Pull request by mtfishman**

### CODE REVIEW

**Comment by mtfishman** [comment]
@dylex I don't see the Jenkins tests running, is it supposed to be enabled now?

**Comment by dylex** [comment]
Yes, but PR triggers are disabled by default. I've enabled them now.

**Comment by mtfishman** [comment]
Got it, thanks! I see that it tried running now. It seems like https://jenkins.flatironinstitute.org isn't accessible right now but maybe that's a different issue.

**Comment by dylex** [comment]
It's working for me, what issue are you seeing?  The build logs are [here](https://jenkins.flatironinstitute.org/job/ITensor/job/ITensorGPU.jl/view/change-requests/job/PR-10/1/console) (mainly `ERROR: Dev path `./ITensorGPU` does not exist`).

**Comment by mtfishman** [comment]
That link hangs for me, and eventually Firefox send me to a page that says "Hmm. We’re having trouble finding that site. We can’t connect to the server at jenkins.flatironinstitute.org."

**Comment by mtfishman** [comment]
(I see where that issue you are seeing is coming from in the workflow, I pushed what I hope is a fix for it.)

**Comment by mtfishman** [comment]
Ok I can access the website now. Thanks again for your help setting this up! I'll look into fixing the workflow.

**Pull request merged**
